-- SECURITY HARDENING MIGRATION
-- Run this in your Supabase SQL Editor

-- 1. Enable RLS on Transactions (if not already)
alter table public.transactions enable row level security;

-- 2. Drop existing policies to avoid conflicts on Transactions
drop policy if exists "Users can view own transactions" on transactions;
drop policy if exists "Users can insert transactions" on transactions;
drop policy if exists "Users can update own transactions" on transactions;
drop policy if exists "Users can insert pending requests" on transactions;

-- 3. Define Strict Read Policy for Transactions
-- Users can see transactions where they are Buyer OR Owner of the project
create policy "Users can view own transactions"
on transactions for select
using (
  auth.uid() = buyer_id 
  OR 
  exists (
    select 1 from projects 
    where projects.id = transactions.project_id 
    and projects.seller_id = auth.uid()
  )
);

-- 4. Define Strict Insert Policy for Transactions
-- Users can ONLY insert 'pending' requests (for collaborations)
-- They CANNOT insert 'completed' transactions (payments/claims) directly
create policy "Users can insert pending requests"
on transactions for insert
with check (
  auth.uid() = buyer_id 
  AND status = 'pending'
);

-- 5. Secure Storage Buckets
-- Remove public access
drop policy if exists "Public Access to project files" on storage.objects;

-- Remove existing "Authenticated users can upload" policy to avoid duplication
drop policy if exists "Authenticated users can upload project files" on storage.objects;
drop policy if exists "Users can view own uploaded files" on storage.objects;

-- Allow Authenticated View (Users who bought/own file)
-- Note: This is complex in SQL. We rely on Signed URLs.
-- So we restrict 'select' to ONLY the owner for management.
-- Download access is handled via Signed URLs generated by Service Role.

create policy "Users can view own uploaded files"
on storage.objects for select
to authenticated
using ( bucket_id = 'project-files' AND auth.uid() = owner );

-- Ensure uploads are still allowed
create policy "Authenticated users can upload project files"
on storage.objects for insert
to authenticated
with check ( bucket_id = 'project-files' );
