'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import {
  Layers,
  IndianRupee,
  Shield,
  Users,
  MessageSquare,
  ArrowRight,
  CheckCircle2,
  Circle,
  X,
  PlusCircle,
  ExternalLink,
} from 'lucide-react';
import Avatar from '@/components/ui/Avatar';
import { Project, Profile } from '@/types/project';
import { Transaction } from '@/types/transaction';
import { CollabRequest } from '@/types/collab';
import { formatINR } from '@/lib/format';
import { getDisplayHandle } from '@/lib/user';
import { ConsoleTab } from './types';
import { useAuth } from '@/context/AuthContext';

interface OverviewTabProps {
  userProfile: Profile | null;
  myProjects: Project[];
  salesTransactions: Transaction[];
  vaultTransactions: Transaction[];
  receivedPitches: CollabRequest[];
  unreadMessagesCount: number;
  isLoading: boolean;
  onTabChange: (tab: ConsoleTab) => void;
}

export default function OverviewTab({
  userProfile,
  myProjects,
  salesTransactions,
  vaultTransactions,
  receivedPitches,
  unreadMessagesCount,
  isLoading,
  onTabChange,
}: OverviewTabProps) {
  const { user } = useAuth();
  const [isChecklistDismissed, setIsChecklistDismissed] = useState(false);

  // Check dismissal state in localStorage
  useEffect(() => {
    if (!user?.id) return;
    const dismissed = localStorage.getItem(`graveyard_dismiss_profile_checklist_${user.id}`);
    if (dismissed === 'true') {
      setIsChecklistDismissed(true);
    }
  }, [user?.id]);

  const handleDismissChecklist = () => {
    if (!user?.id) return;
    localStorage.setItem(`graveyard_dismiss_profile_checklist_${user.id}`, 'true');
    setIsChecklistDismissed(true);
  };

  // Metrics
  const totalEarningsPaise = salesTransactions.reduce((acc, t) => acc + (t.amount || 0), 0);
  const activeListingsCount = myProjects.filter((p) => !p.is_sold && !p.is_collab_filled && !p.is_archived).length;
  const totalSalesCount = salesTransactions.length;
  const totalClaimsCount = vaultTransactions.filter((t) => t.kind === 'adopt').length;
  const openPitchesCount = receivedPitches.filter((p) => p.status === 'pending').length;

  // Profile completeness checklist calculation
  const rawUsername = userProfile?.username || user?.username || '';
  const isAutoGeneratedHandle = /^[a-z0-9.]+_\d{3,4}$/i.test(rawUsername);
  const hasRealUsername = Boolean(rawUsername && !isAutoGeneratedHandle);
  const hasBio = Boolean(userProfile?.bio && userProfile.bio.trim().length > 0);
  const hasAvatar = Boolean(userProfile?.avatar_url && !userProfile.avatar_url.includes('dicebear.com/7.x/shapes'));
  const hasContact = Boolean(userProfile?.contact_info && userProfile.contact_info.trim().length > 0);
  const hasCreatedListing = myProjects.length > 0;

  const checklistItems = [
    { id: 'username', label: 'Choose a real username', done: hasRealUsername, action: () => onTabChange('settings') },
    { id: 'bio', label: 'Add a bio', done: hasBio, action: () => onTabChange('settings') },
    { id: 'avatar', label: 'Add an avatar', done: hasAvatar, action: () => onTabChange('settings') },
    { id: 'contact', label: 'Add a contact handle', done: hasContact, action: () => onTabChange('settings') },
    { id: 'listing', label: 'Create your first listing', done: hasCreatedListing, href: '/submit' },
  ];

  const completedCount = checklistItems.filter((i) => i.done).length;
  const isProfileComplete = completedCount === checklistItems.length;

  if (isLoading) {
    return (
      <div className="space-y-8 animate-pulse">
        <div className="h-10 w-48 bg-surface-2 rounded-lg" />
        <div className="grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-6 gap-3 sm:gap-4">
          {Array.from({ length: 6 }).map((_, idx) => (
            <div key={idx} className="h-32 bg-surface rounded-card border border-line" />
          ))}
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="h-64 bg-surface rounded-card border border-line" />
          <div className="h-64 bg-surface rounded-card border border-line" />
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-in fade-in duration-200">
      {/* Header Row: Title & Subtitle */}
      <div>
        <h1 className="font-display text-2xl sm:text-3xl lg:text-4xl font-semibold text-white tracking-tight">
          Overview
        </h1>
        <p className="font-sans text-sm text-muted mt-1.5">
          A snapshot of your listings, sales and messages.
        </p>
      </div>

      {/* Dismissible "Complete your profile" card (only when incomplete and not dismissed) */}
      {!isProfileComplete && !isChecklistDismissed && (
        <section
          aria-label="Profile completion checklist"
          className="p-5 sm:p-6 bg-surface-2/70 rounded-card border border-line relative overflow-hidden"
        >
          <div className="flex items-start justify-between gap-4">
            <div className="space-y-1">
              <div className="flex items-center gap-2.5">
                <span className="font-mono text-xs font-semibold uppercase tracking-wider text-[#ff5555]">
                  Get started
                </span>
                <span className="text-xs text-muted">
                  • {completedCount} of {checklistItems.length} completed
                </span>
              </div>
              <h2 className="font-display text-lg font-semibold text-white">
                Complete your profile
              </h2>
            </div>
            <button
              type="button"
              onClick={handleDismissChecklist}
              className="p-1.5 rounded-lg text-muted hover:text-white hover:bg-white/5 transition-colors"
              aria-label="Dismiss checklist"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          {/* Progress Bar */}
          <div className="w-full bg-white/10 rounded-full h-1.5 mt-4 overflow-hidden">
            <div
              className="bg-brand-red h-full rounded-full transition-all duration-300"
              style={{ width: `${(completedCount / checklistItems.length) * 100}%` }}
            />
          </div>

          {/* Checklist items */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2.5 mt-4 pt-2">
            {checklistItems.map((item) => (
              <div key={item.id} className="flex items-center gap-2.5 text-xs font-sans">
                {item.done ? (
                  <CheckCircle2 className="w-4 h-4 text-[#39ff14] shrink-0" />
                ) : (
                  <Circle className="w-4 h-4 text-muted/50 shrink-0" />
                )}
                {item.done ? (
                  <span className="text-muted line-through">{item.label}</span>
                ) : item.href ? (
                  <Link
                    href={item.href}
                    className="text-white hover:text-brand-red underline underline-offset-2 transition-colors"
                  >
                    {item.label}
                  </Link>
                ) : (
                  <button
                    type="button"
                    onClick={item.action}
                    className="text-white hover:text-brand-red underline underline-offset-2 transition-colors text-left"
                  >
                    {item.label}
                  </button>
                )}
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Stat Grid: 6 cards (2 cols mobile, 3 tablet, 6 xl). No orphan card! */}
      <div className="grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-6 gap-3 sm:gap-4">
        {/* Card 1: Earnings (test mode) */}
        <div className="p-4 sm:p-5 bg-surface rounded-card border border-line flex flex-col justify-between min-h-[140px]">
          <div className="flex items-start justify-between gap-2">
            <span
              title="Earnings (test mode)"
              className="font-sans font-medium text-xs sm:text-sm text-muted truncate"
            >
              Earnings (test mode)
            </span>
            <div className="w-7 h-7 rounded-full bg-white/5 flex items-center justify-center shrink-0 text-muted">
              <IndianRupee className="w-3.5 h-3.5" />
            </div>
          </div>
          <div className="my-2">
            <span className="font-display text-2xl sm:text-3xl font-bold text-white tabular-nums">
              {formatINR(totalEarningsPaise)}
            </span>
          </div>
          <div className="min-h-[2rem] flex items-end">
            <p className="font-sans text-xs text-muted/80 leading-snug">
              From test-mode sales
            </p>
          </div>
        </div>

        {/* Card 2: Active listings */}
        <div className="p-4 sm:p-5 bg-surface rounded-card border border-line flex flex-col justify-between min-h-[140px]">
          <div className="flex items-start justify-between gap-2">
            <span
              title="Active listings"
              className="font-sans font-medium text-xs sm:text-sm text-muted truncate"
            >
              Active listings
            </span>
            <div className="w-7 h-7 rounded-full bg-white/5 flex items-center justify-center shrink-0 text-muted">
              <Layers className="w-3.5 h-3.5" />
            </div>
          </div>
          <div className="my-2 flex items-center gap-2">
            <span className="font-display text-2xl sm:text-3xl font-bold text-white tabular-nums">
              {activeListingsCount}
            </span>
            {activeListingsCount > 0 && <span className="w-1.5 h-1.5 rounded-full bg-[#39ff14]" />}
          </div>
          <div className="min-h-[2rem] flex items-end">
            <p className="font-sans text-xs text-muted/80 leading-snug">
              Live on the marketplace
            </p>
          </div>
        </div>

        {/* Card 3: Sales */}
        <div className="p-4 sm:p-5 bg-surface rounded-card border border-line flex flex-col justify-between min-h-[140px]">
          <div className="flex items-start justify-between gap-2">
            <span
              title="Sales"
              className="font-sans font-medium text-xs sm:text-sm text-muted truncate"
            >
              Sales
            </span>
            <div className="w-7 h-7 rounded-full bg-white/5 flex items-center justify-center shrink-0 text-muted">
              <IndianRupee className="w-3.5 h-3.5" />
            </div>
          </div>
          <div className="my-2 flex items-center gap-2">
            <span className="font-display text-2xl sm:text-3xl font-bold text-white tabular-nums">
              {totalSalesCount}
            </span>
            {totalSalesCount > 0 && <span className="w-1.5 h-1.5 rounded-full bg-[#39ff14]" />}
          </div>
          <div className="min-h-[2rem] flex items-end">
            <p className="font-sans text-xs text-muted/80 leading-snug">
              Projects you've sold
            </p>
          </div>
        </div>

        {/* Card 4: Claims */}
        <div className="p-4 sm:p-5 bg-surface rounded-card border border-line flex flex-col justify-between min-h-[140px]">
          <div className="flex items-start justify-between gap-2">
            <span
              title="Claims"
              className="font-sans font-medium text-xs sm:text-sm text-muted truncate"
            >
              Claims
            </span>
            <div className="w-7 h-7 rounded-full bg-white/5 flex items-center justify-center shrink-0 text-muted">
              <Shield className="w-3.5 h-3.5" />
            </div>
          </div>
          <div className="my-2 flex items-center gap-2">
            <span className="font-display text-2xl sm:text-3xl font-bold text-white tabular-nums">
              {totalClaimsCount}
            </span>
            {totalClaimsCount > 0 && <span className="w-1.5 h-1.5 rounded-full bg-[#fbbf24]" />}
          </div>
          <div className="min-h-[2rem] flex items-end">
            <p className="font-sans text-xs text-muted/80 leading-snug">
              Free forks you've claimed
            </p>
          </div>
        </div>

        {/* Card 5: Collab requests */}
        <div className="p-4 sm:p-5 bg-surface rounded-card border border-line flex flex-col justify-between min-h-[140px]">
          <div className="flex items-start justify-between gap-2">
            <span
              title="Collab requests"
              className="font-sans font-medium text-xs sm:text-sm text-muted truncate"
            >
              Collab requests
            </span>
            <div className="w-7 h-7 rounded-full bg-white/5 flex items-center justify-center shrink-0 text-muted">
              <Users className="w-3.5 h-3.5" />
            </div>
          </div>
          <div className="my-2 flex items-center gap-2">
            <span className="font-display text-2xl sm:text-3xl font-bold text-white tabular-nums">
              {openPitchesCount}
            </span>
            {openPitchesCount > 0 && <span className="w-1.5 h-1.5 rounded-full bg-[#3b82f6]" />}
          </div>
          <div className="min-h-[2rem] flex items-end">
            <p className="font-sans text-xs text-muted/80 leading-snug">
              Waiting for your reply
            </p>
          </div>
        </div>

        {/* Card 6: Unread messages */}
        <div className="p-4 sm:p-5 bg-surface rounded-card border border-line flex flex-col justify-between min-h-[140px]">
          <div className="flex items-start justify-between gap-2">
            <span
              title="Unread messages"
              className="font-sans font-medium text-xs sm:text-sm text-muted truncate"
            >
              Unread messages
            </span>
            <div className="w-7 h-7 rounded-full bg-white/5 flex items-center justify-center shrink-0 text-muted">
              <MessageSquare className="w-3.5 h-3.5" />
            </div>
          </div>
          <div className="my-2 flex items-center gap-2">
            <span className="font-display text-2xl sm:text-3xl font-bold text-white tabular-nums">
              {unreadMessagesCount}
            </span>
            {unreadMessagesCount > 0 && <span className="w-1.5 h-1.5 rounded-full bg-[#ff5555]" />}
          </div>
          <div className="min-h-[2rem] flex items-end">
            <p className="font-sans text-xs text-muted/80 leading-snug">
              Across all conversations
            </p>
          </div>
        </div>
      </div>

      {/* Second Row: Two Equal Columns (Recent Sales & Collab Requests) */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Recent sales Card */}
        <section aria-label="Recent sales" className="p-6 bg-surface rounded-card border border-line space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="font-display text-lg font-semibold text-white">Recent sales</h2>
            {salesTransactions.length > 0 && (
              <button
                type="button"
                onClick={() => onTabChange('sales')}
                className="font-sans font-medium text-xs text-muted hover:text-white flex items-center gap-1 transition-colors"
              >
                View all <ArrowRight className="w-3.5 h-3.5" />
              </button>
            )}
          </div>

          {salesTransactions.length === 0 ? (
            <div className="py-8 text-center space-y-3">
              <div className="w-10 h-10 rounded-full bg-white/5 flex items-center justify-center mx-auto text-muted">
                <IndianRupee className="w-5 h-5" />
              </div>
              <div className="space-y-1 max-w-xs mx-auto">
                <p className="font-sans font-medium text-sm text-white">No sales yet</p>
                <p className="font-sans text-xs text-muted">
                  When someone buys or claims one of your projects, it shows up here.
                </p>
              </div>
              <div className="pt-2">
                {myProjects.length > 0 ? (
                  <button
                    type="button"
                    onClick={() => onTabChange('listings')}
                    className="inline-flex items-center gap-1.5 px-4 py-2 rounded-full bg-white/10 hover:bg-white/20 text-white font-sans text-xs font-semibold transition-colors"
                  >
                    View my listings
                  </button>
                ) : (
                  <Link
                    href="/submit"
                    className="inline-flex items-center gap-1.5 px-4 py-2 rounded-full bg-white text-black hover:bg-neutral-200 font-sans text-xs font-semibold transition-colors shadow-sm"
                  >
                    Create a listing
                  </Link>
                )}
              </div>
            </div>
          ) : (
            <div className="divide-y divide-line">
              {salesTransactions.slice(0, 5).map((tx) => (
                <div key={tx.id} className="py-3 flex items-center justify-between gap-3 text-xs font-sans">
                  <div className="flex items-center gap-3 min-w-0">
                    <Avatar username={tx.buyer?.username} size={28} />
                    <div className="min-w-0">
                      <span className="font-medium text-white truncate block">
                        {tx.project?.title || 'Unknown project'}
                      </span>
                      <span className="text-muted text-[11px] block">
                        to {getDisplayHandle(tx.buyer)}
                      </span>
                    </div>
                  </div>
                  <div className="text-right shrink-0">
                    <span className="font-mono font-medium text-white block">
                      {tx.kind === 'adopt' ? 'Free Claim' : formatINR(tx.amount || 0)}
                    </span>
                    <span className="text-[10px] text-muted block">
                      {new Date(tx.created_at).toLocaleDateString()}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>

        {/* Collab requests Card */}
        <section aria-label="Collab requests" className="p-6 bg-surface rounded-card border border-line space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="font-display text-lg font-semibold text-white">Collab requests</h2>
            {receivedPitches.length > 0 && (
              <button
                type="button"
                onClick={() => onTabChange('collabs')}
                className="font-sans font-medium text-xs text-muted hover:text-white flex items-center gap-1 transition-colors"
              >
                View all <ArrowRight className="w-3.5 h-3.5" />
              </button>
            )}
          </div>

          {receivedPitches.length === 0 ? (
            <div className="py-8 text-center space-y-3">
              <div className="w-10 h-10 rounded-full bg-white/5 flex items-center justify-center mx-auto text-muted">
                <Users className="w-5 h-5" />
              </div>
              <div className="space-y-1 max-w-xs mx-auto">
                <p className="font-sans font-medium text-sm text-white">No requests yet</p>
                <p className="font-sans text-xs text-muted">
                  List a project as Seeking partner to receive pitches.
                </p>
              </div>
              <div className="pt-2">
                <Link
                  href="/submit?mode=collab"
                  className="inline-flex items-center gap-1.5 px-4 py-2 rounded-full bg-white text-black hover:bg-neutral-200 font-sans text-xs font-semibold transition-colors shadow-sm"
                >
                  Create a collab listing
                </Link>
              </div>
            </div>
          ) : (
            <div className="divide-y divide-line">
              {receivedPitches.slice(0, 5).map((pitch) => (
                <div key={pitch.id} className="py-3 flex items-center justify-between gap-3 text-xs font-sans">
                  <div className="flex items-center gap-3 min-w-0">
                    <Avatar username={pitch.applicant?.username} size={28} />
                    <div className="min-w-0">
                      <span className="font-medium text-white truncate block">
                        {pitch.project?.title || 'Collab listing'}
                      </span>
                      <span className="text-muted text-[11px] block">
                        from {getDisplayHandle(pitch.applicant)}
                      </span>
                    </div>
                  </div>
                  <div className="text-right shrink-0">
                    <span
                      className={`inline-block px-2 py-0.5 rounded-full text-[10px] font-mono font-medium ${
                        pitch.status === 'accepted'
                          ? 'bg-[#39ff14]/10 text-[#39ff14]'
                          : pitch.status === 'rejected'
                            ? 'bg-white/5 text-muted'
                            : 'bg-[#3b82f6]/10 text-[#60a5fa]'
                      }`}
                    >
                      {pitch.status}
                    </span>
                    <span className="text-[10px] text-muted block mt-0.5">
                      {new Date(pitch.created_at).toLocaleDateString()}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>
      </div>
    </div>
  );
}
